import json

path = "/home/wuct/ALICE/reps/cfAnRes/tools/notebook/2pc/smooth/smooth_temp.ipynb"
nb = json.loads(open(path, 'r').read())

new_source = []
new_source.append('import os\n')
new_source.append('import ROOT\n')
new_source.append('import numpy as np\n')
new_source.append('\n')
new_source.append('path = "/home/wuct/ALICE/reps/cfAnRes/tools/notebook/2pc/smooth"\n')
new_source.append('outPath = f"{path}/comparison"\n')
new_source.append('os.makedirs(outPath, exist_ok=True)\n')
new_source.append('\n')
new_source.append('# 1. 严格对齐文件\n')
new_source.append("subdirs = ['raw', 'rebin2', 'rebin4']\n")
new_source.append('root_files = {d: [] for d in subdirs}\n')
new_source.append('\n')
new_source.append('for d in subdirs:\n')
new_source.append('    full_dir = os.path.join(path, d)\n')
new_source.append('    if os.path.exists(full_dir):\n')
new_source.append('        for file in os.listdir(full_dir):\n')
new_source.append('            if file.endswith(".root"):\n')
new_source.append('                root_files[d].append(os.path.join(full_dir, file))\n')
new_source.append('        root_files[d].sort()\n')
new_source.append('\n')
new_source.append("num_plots = min(len(root_files['raw']), len(root_files['rebin2']), len(root_files['rebin4']))\n")
new_source.append('print(f"Aligned bins to compare: {num_plots}")\n')
new_source.append('\n')
new_source.append('# 采样：在 [-pi/2, 3*pi/2] 之间均匀采样 500 个点\n')
new_source.append('x_samples = np.linspace(-ROOT.TMath.Pi()/2, 3*ROOT.TMath.Pi()/2, 500)\n')
new_source.append('\n')
new_source.append('graphs = {d: [] for d in subdirs}\n')
new_source.append('\n')
new_source.append('print("Sampling fit functions via Eval...")\n')
new_source.append('for subdir in subdirs:\n')
new_source.append('    for idx, file in enumerate(root_files[subdir][:num_plots]):\n')
new_source.append('        root_file = ROOT.TFile.Open(file, "READ")\n')
new_source.append('        if not root_file or root_file.IsZombie():\n')
new_source.append('            continue\n')
new_source.append('            \n')
new_source.append('        dataHistogram = root_file.Get("dataHistogram")\n')
new_source.append('        if not dataHistogram:\n')
new_source.append('            root_file.Close()\n')
new_source.append('            continue\n')
new_source.append('            \n')
new_source.append('        # 从 ListOfFunctions 里提取 fitFunc\n')
new_source.append('        fit_func = None\n')
new_source.append('        for func in dataHistogram.GetListOfFunctions():\n')
new_source.append('            if "fitFunc" in func.GetName() or isinstance(func, ROOT.TF1):\n')
new_source.append('                fit_func = func\n')
new_source.append('                break\n')
new_source.append('                \n')
new_source.append('        if fit_func:\n')
new_source.append('            # 采样成纯数据直方图，彻底避免 TFormula 解析\n')
new_source.append('            h_sample = ROOT.TH1D(f"h_sample_{subdir}_{idx}", "", len(x_samples)-1, -ROOT.TMath.Pi()/2, 3*ROOT.TMath.Pi()/2)\n')
new_source.append('            h_sample.SetDirectory(0)\n')
new_source.append('            for bin_idx, x_val in enumerate(x_samples):\n')
new_source.append('                y_val = fit_func.Eval(x_val)\n')
new_source.append('                h_sample.SetBinContent(bin_idx + 1, y_val)\n')
new_source.append('            graphs[subdir].append(h_sample)\n')
new_source.append('        else:\n')
new_source.append('            print(f"Warning: No fit function in {file}")\n')
new_source.append('            \n')
new_source.append('        root_file.Close()\n')
new_source.append('\n')
new_source.append('print("Sampling complete.")\n')
new_source.append('\n')
new_source.append('# 2. 画图对比\n')
new_source.append('print("\\nStarting Plotting Loop...")\n')
new_source.append('\n')
new_source.append('for iPt in range(num_plots):\n')
new_source.append('    canvas = ROOT.TCanvas(f"canvas_{iPt}", f"Fit Comparison Bin_{iPt}", 1600, 1200)\n')
new_source.append('    \n')
new_source.append("    graphs['raw'][iPt].SetLineColor(ROOT.kRed)\n")
new_source.append("    graphs['raw'][iPt].SetLineWidth(4)\n")
new_source.append('    \n')
new_source.append("    graphs['rebin2'][iPt].SetLineColor(ROOT.kBlue)\n")
new_source.append("    graphs['rebin2'][iPt].SetLineWidth(4)\n")
new_source.append("    graphs['rebin2'][iPt].SetLineStyle(7)\n")
new_source.append('    \n')
new_source.append("    graphs['rebin4'][iPt].SetLineColor(ROOT.kGreen+2)\n")
new_source.append("    graphs['rebin4'][iPt].SetLineWidth(4)\n")
new_source.append("    graphs['rebin4'][iPt].SetLineStyle(9)\n")
new_source.append('    \n')
new_source.append('    max_y = max(graphs["raw"][iPt].GetMaximum(), graphs["rebin2"][iPt].GetMaximum(), graphs["rebin4"][iPt].GetMaximum())\n')
new_source.append('    min_y = min(graphs["raw"][iPt].GetMinimum(), graphs["rebin2"][iPt].GetMinimum(), graphs["rebin4"][iPt].GetMinimum())\n')
new_source.append('    graphs["raw"][iPt].SetMaximum(max_y + 0.15 * (max_y - min_y))\n')
new_source.append('    graphs["raw"][iPt].SetMinimum(min_y - 0.05 * (max_y - min_y))\n')
new_source.append('    \n')
new_source.append('    graphs["raw"][iPt].Draw("HIST")\n')
new_source.append('    graphs["rebin2"][iPt].Draw("HIST Same")\n')
new_source.append('    graphs["rebin4"][iPt].Draw("HIST Same")\n')
new_source.append('    \n')
new_source.append('    leg = ROOT.TLegend(0.68, 0.78, 0.93, 0.93)\n')
new_source.append('    leg.SetFillStyle(0)\n')
new_source.append('    leg.SetBorderSize(0)\n')
new_source.append('    leg.SetTextSize(0.025)\n')
new_source.append('    \n')
new_source.append("    filename = os.path.basename(root_files['raw'][iPt])\n")
new_source.append('    pt_info = filename.split("fit_")[-1].split("_PtHadBin")[0]\n')
new_source.append('    leg.SetHeader(f"Bin {iPt}: {pt_info}", "C")\n')
new_source.append('    \n')
new_source.append("    leg.AddEntry(graphs['raw'][iPt], \"Raw Fit\", \"L\")\n")
new_source.append("    leg.AddEntry(graphs['rebin2'][iPt], \"Rebin 2 Fit\", \"L\")\n")
new_source.append("    leg.AddEntry(graphs['rebin4'][iPt], \"Rebin 4 Fit\", \"L\")\n")
new_source.append('    leg.Draw()\n')
new_source.append('    \n')
new_source.append('    canvas.Modified()\n')
new_source.append('    canvas.Update()\n')
new_source.append('    \n')
new_source.append('    canvas.SaveAs(f"{outPath}/fit_comparison_{iPt}.png")\n')
new_source.append('    print(f"Saved: {outPath}/fit_comparison_{iPt}.png")\n')
new_source.append('\n')
new_source.append('print("\\nAll comparison plots exported successfully!")\n')

nb['cells'][3]['source'] = new_source

text = json.dumps(nb, indent=1, ensure_ascii=False)
with open(path, 'w') as f:
    f.write(text)
    f.write('\n')

print("Done! Cell 3 rewritten with Eval-sampling approach.")
