# Meta config
META_CONFIG: &META_CONFIG
  AlienOutputDirs: [] # output dirs to download from
  LocalPath: '' # local path to save files
  ForceStage: True # in case files are not merged properly, force downloading staged files
  FileName: AnalysisResults.root
  RunNumMatch: False # if True, save files in subdirectories named by run number, e.g. LocalPath/RunNum/iFile/FileName
  RunList: [
  ]
  # AnalysisResults.root
  # AO2D.root
  # AA for AnalysisResults.root and AO2D.root

# predefined task base
AR: &AR
  FileName: AnalysisResults.root
AO: &AO
  FileName: AO2D.root
AA: &AA
  FileName: AA

# tasks
task1:
  <<: *META_CONFIG
  <<: *AA # *AR or *AO or *AA
  AlienOutputDirs: [
    /alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476493/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476492/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476491/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476490/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476489/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476488/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476487/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476486/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476485/AOD
  ]
  RunNumMatch: True
  RunList: [
    564445,564430,564414,564400,564387,564374,564373,564359,564356
  ]
  LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fifth/SE/k020

task2:
  <<: *META_CONFIG
  <<: *AA # *AR or *AO or *AA
  AlienOutputDirs: [
    /alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476563/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476562/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476561/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476560/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476559/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476558/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476557/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476556/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476555/AOD
  ]
  RunNumMatch: True
  RunList: [
    564445,564430,564414,564400,564387,564374,564373,564359,564356
  ]
  LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fifth/SE/k20100

task3:
  <<: *META_CONFIG
  <<: *AA # *AR or *AO or *AA
  AlienOutputDirs: [
    /alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476484/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476483/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476482/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476481/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476480/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476306/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476305/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476304/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476303/AOD
  ]
  RunNumMatch: True
  RunList: [
    564445,564430,564414,564400,564387,564374,564373,564359,564356
  ]
  LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fifth/ME/k020

task4:
  <<: *META_CONFIG
  <<: *AA # *AR or *AO or *AA
  AlienOutputDirs: [
    /alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476554/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476553/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476500/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476499/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476498/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476497/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476496/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476495/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0447/hy_4476494/AOD
  ]
  RunNumMatch: True
  RunList: [
    564445,564430,564414,564400,564387,564374,564373,564359,564356
  ]
  LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fifth/ME/k20100

# task1: &task1
#   <<: *META_CONFIG
#   <<: *AO # *AR or *AO or *AA
#   AlienOutputDirs: [
#     /alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152527/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151980/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151979/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151963/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151955/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151954/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151953/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151952/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151951/AOD
#   ]
#   LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fthlook_Biao/large/SE/k020
# task2: &task2
#   <<: *task1
#   AlienOutputDirs: [
#     /alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4153056/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4153037/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152699/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152674/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152660/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152659/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152658/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152657/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152656/AOD
#   ]
#   LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fthlook_Biao/large/SE/k20100
# task3: &task3
#   <<: *task1
#   AlienOutputDirs: [
#     /alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151950/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151930/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151929/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151832/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151831/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151797/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151796/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151795/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4151794/AOD
#   ]
#   LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fthlook_Biao/large/ME/k020
# task4: &task4
#   <<: *task1
#   AlienOutputDirs: [
#     /alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152655/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152546/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152545/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152537/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152532/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152531/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152530/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152529/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0415/hy_4152528/AOD
#   ]
#   LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/fthlook_Biao/large/ME/k20100