AlienOutputDirs: [
  /alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133263,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133262,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133261,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133260,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133003,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133002,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133001,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5133000,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5132999,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5132998,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5132997,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5132996,/alice/cern.ch/user/a/alihyperloop/jobs/0513/hy_5132995
]
LocalPath: /home/wuct/MetaData/MC/production/ppref/charm_baryon/25g1b
ForceStage: False # in case files are not merged properly, force downloading staged files
FileName: AnalysisResults.root
RunNumMatch: True
sample: 3 # sample files to download with a gap of N
allowance: 200 # number of files to keep between each sampled file, -1 means include all files
RunList: [
  559456,559444,559443,559437,559423,559410,559409,559408,559387,559385,559362,559361,559348
]
# AnalysisResults.root
# AO2D.root
# AA for AnalysisResults.root and AO2D.root